### ISSUE TITLE
Update copyright date

### ISSUE THREAD

**Issue by CreativeQuilt** [twitter/twitter.github.io#111] opened 2021-04-08 17:23 UTC
**Describe the bug**
The copyright date is outdated
**To Reproduce**
1. Go to twitter.github.io
2. Scroll down to '....'
3. See (c) 2018

**Expected behavior**
It should say (c) 2021

**Comment by andypiper** [comment] 2021-04-08 21:26
duplicate of #87 and #101

**Closed by andypiper** 2021-04-08 21:26 UTC
